/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frmProyecto;

import clProyecto.dbConection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;

/**
 *
 * @author David
 */
public class frmAdmin extends javax.swing.JFrame {

    
    int idU;
 
    /**
     * Creates new form frmAdmin
     */
    public frmAdmin(int idUsuario) {
        initComponents();
        idU=idUsuario;
        buscarNombre();
        sesion();
    }
    
    
    public void sesion(){
    
    if(idU>1){
        menuReportes.setVisible(false);
        lbTitulo.setText("BEINVENIDO");
    }
    
    }
    
    public void  buscarNombre(){
          try { 
            Connection db = dbConection.conectar();

            CallableStatement cs = db.prepareCall("CALL ObtenerNombreUsuario(?, ?)");
            cs.setInt(1, idU);  
            cs.registerOutParameter(2, Types.VARCHAR);  

            cs.execute();

            String nombreUsuario = cs.getString(2);  
            lbNombreUsuario.setText(nombreUsuario);  

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        lbNombreUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        menuAdmin = new javax.swing.JMenuBar();
        menuReportes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        tarifasitem = new javax.swing.JMenuItem();
        menuEditores = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("USUARIO:");

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("BIENVENIDO ADMIN");
        lbTitulo.setToolTipText("");
        lbTitulo.setPreferredSize(new java.awt.Dimension(69, 60));

        menuReportes.setText("ADMIN");

        jMenuItem2.setText("REPORTES INDIVIDUALES");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem2);

        tarifasitem.setText("TARIFAS");
        tarifasitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifasitemActionPerformed(evt);
            }
        });
        menuReportes.add(tarifasitem);

        menuAdmin.add(menuReportes);

        menuEditores.setText("MANEJO");

        jMenuItem7.setText("INGRESAR VEHICULO");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuEditores.add(jMenuItem7);

        jMenuItem8.setText("SACAR VEHICULO");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuEditores.add(jMenuItem8);

        menuAdmin.add(menuEditores);

        menuSalir.setText("USER");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });

        jMenuItem1.setText("CERRAR SESIÓN");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSalir.add(jMenuItem1);

        jMenuItem3.setText("DATOS USUARIO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuSalir.add(jMenuItem3);

        menuAdmin.add(menuSalir);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(308, 308, 308))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_menuSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
               frmIniciarSecion fminicio = new frmIniciarSecion();
                fminicio.setVisible(true);

               this.dispose();
         
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         frmReportesIndividuales fmRI = new  frmReportesIndividuales(idU);
                fmRI.setVisible(true);

                this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frmEditarDatos frmED = new frmEditarDatos(idU);
        frmED.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
                frmIngresarVehiculo fmingresar = new  frmIngresarVehiculo(idU);
                fmingresar.setVisible(true);

                this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        frmSacarVehiculo frmsacar= new frmSacarVehiculo(idU);
        frmsacar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void tarifasitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifasitemActionPerformed
        // TODO add your handling code here:
        frmTarifas frmTari = new frmTarifas(idU);
        frmTari.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tarifasitemActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu menuEditores;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem tarifasitem;
    // End of variables declaration//GEN-END:variables
}
