/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frmProyecto;

import clProyecto.*;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author David
 */
public class frmIngresarVehiculo extends javax.swing.JFrame {
    
        String metodoPago,placa,tipoVhiculo, nombre ;
       double totalPago=0;
       int idU,tarifa;
    String[] metodo={"Tarjeta","Efectivo"};
    Ingresar in= new Ingresar();
    

    /**
     * Creates new form frmIngresarVehiculo
     */
    public frmIngresarVehiculo(int id) {
        initComponents();
        txtPlaca.setText("");
        this.idU=id;
        llenarComboTipo();
      llenarComboMetodo();
      buscarNombre();
    }
     public void llenarComboMetodo(){
        comboMetodoPago.removeAllItems();
        comboMetodoPago.addItem("Seleccione...");
        for (int i = 0; i < metodo.length; i++) {
            comboMetodoPago.addItem(metodo[i]);
            
        }
    }
      public void  buscarNombre(){
          try { 
            Connection db = dbConection.conectar();

            CallableStatement cs = db.prepareCall("CALL ObtenerNombreUsuario(?, ?)");
            cs.setInt(1, idU);  
            cs.registerOutParameter(2, Types.VARCHAR);  

            cs.execute();

            String nombreUsuario = cs.getString(2);  
            nombre=nombreUsuario;  

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
    }

    public void llenarComboTipo() {
    comboTipoVehiculo.removeAllItems();
    comboTipoVehiculo.addItem("Seleccione...");

    try {
        Connection db = dbConection.conectar();
        CallableStatement cs = db.prepareCall("CALL ObtenerTiposVehiculo()");
        ResultSet rs = cs.executeQuery();

        while (rs.next()) {
            comboTipoVehiculo.addItem(rs.getString("tipoVehiculo"));
        }

        rs.close();
        cs.close();
        db.close();

    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
    
     public void guardar(){
        
        llenar();
         if(    placa != null && !placa.isEmpty() &&
                tipoVhiculo != null && !tipoVhiculo.isEmpty() &&
                metodoPago != null && !metodoPago.isEmpty())               
               {

                  in.igresarVehiculo(placa, tipoVhiculo);
                  in.transacciones(placa,tarifa, metodoPago, totalPago,nombre,null);
                  
                  txtPlaca.setText("");
                  llenarComboTipo();
                 llenarComboMetodo();
           
        }else{
             
              JOptionPane.showMessageDialog(rootPane, "faltan campos por llenar");
            
        }
        
        
              
    
    }

private String validarLongitud(JTextField campo, int maxLongitud, String mensajeError) {
    String texto = campo.getText();
    if (texto.length() <= maxLongitud) {
        return texto.toUpperCase();
    } else {
        JOptionPane.showMessageDialog(rootPane, mensajeError);
        return "";
    }
}

    
    public void llenar() {
    placa = validarLongitud(txtPlaca, 6, "La placa ha superado el límite...");
    tipoVhiculo = comboTipoVehiculo.getSelectedIndex() > 0 ? comboTipoVehiculo.getSelectedItem().toString() : null;
    metodoPago = comboMetodoPago.getSelectedIndex() > 0 ? metodo[comboMetodoPago.getSelectedIndex() - 1] : null;
    tarifa = 0;
    totalPago = 0;

    if (tipoVhiculo != null) {
        try {
            Connection db = dbConection.conectar();
            CallableStatement cs = db.prepareCall("CALL ObtenerTarifaPorTipo(?, ?)");

            cs.setString(1, tipoVhiculo);
            cs.registerOutParameter(2, Types.INTEGER); 

            cs.execute();

            tarifa = cs.getInt(2); 

            cs.close();
            db.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
    
  
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        comboTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboMetodoPago = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("TIPO DE VEHICULO");

        txtPlaca.setText("Ingrese su placa...");

        jLabel13.setText("PLACA");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        comboTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese los datos esperados");

        comboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Datos del vehiculo");

        jLabel12.setText("METODO DE PAGO");

        btnSalir.setText("Salir");
        btnSalir.setVerifyInputWhenFocusTarget(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnSacar.setText("SacarVehiculo");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel11))
                                .addComponent(comboTipoVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel12))
                                .addComponent(comboMetodoPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            
            guardar();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "faltan campos por llenar");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         frmAdmin fmadmin = new  frmAdmin(idU);
                fmadmin.setVisible(true);

                this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        // TODO add your handling code here:
        frmSacarVehiculo frmsacar= new frmSacarVehiculo(idU);
        frmsacar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngresarVehiculo(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboMetodoPago;
    private javax.swing.JComboBox<String> comboTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
