/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frmProyecto;

import clProyecto.Ingresar;
import clProyecto.dbConection;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class frmInicidentes extends javax.swing.JFrame {
    
    ArrayList<Integer> idTransacicones;
    Ingresar in= new Ingresar();
    String[] tiposIncidentes = {
    "Multa por mal estacionamiento",
    "Daño a otro vehículo",
    "Choque dentro del parqueadero",
    "Comportamiento inapropiado",
    "Daño a infraestructura",
    "No pago",
    "Pérdida de ticket",
    "Exceso de tiempo sin autorización",
    "Otros"
    };
    String nombre,tipoIncidente,descripcion;
    int idTransaccion,idU;
    double monto;
            

    public frmInicidentes(int id) {
        initComponents();
        idTransacicones = new ArrayList<>();
        txtMonto.setText("");
        this.idU=id;
        buscarNombre();
        llenarComboVehiculosActivos();
        llenarComboTipoIncidente();
    }
    
    public void llenarComboVehiculosActivos() {
    comboTipo.removeAllItems();
    comboTipo.addItem("Seleccione...");
    idTransacicones.clear();
    try {
        Connection db = dbConection.conectar();
        CallableStatement cs = db.prepareCall("CALL ObtenerVehiculosConTransaccionActiva()");
        ResultSet rs = cs.executeQuery();

        while (rs.next()) {
            String placa = rs.getString("placa");
            int idTransaccion = rs.getInt("idTransaccion");

            comboTipo.addItem(placa); 
            idTransacicones.add(idTransaccion); 
        }

        rs.close();
        cs.close();
        db.close();

    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
   
    public void llenarComboTipoIncidente() {
    comboTipoIncidente.removeAllItems();
    comboTipoIncidente.addItem("Seleccione...");

    for (String tipo : tiposIncidentes) {
        comboTipoIncidente.addItem(tipo);
    }
}
public void  buscarNombre(){
          try { 
            Connection db = dbConection.conectar();

            CallableStatement cs = db.prepareCall("CALL ObtenerNombreUsuario(?, ?)");
            cs.setInt(1, idU);  
            cs.registerOutParameter(2, Types.VARCHAR);  

            cs.execute();

            String nombreUsuario = cs.getString(2);  
            nombre=nombreUsuario;  

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
    }
public boolean validarCamposIncidente() {

    String placaSeleccionada = comboTipo.getSelectedItem().toString();
    String tipoIncidenteSeleccionado = comboTipoIncidente.getSelectedItem().toString();
    String descripcion = txtDescripcion.getText().trim(); 
    String montoTexto = txtMonto.getText().trim();


    if (comboTipo.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar una placa.");
        return false;
    }

    if (comboTipoIncidente.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de incidente.");
        return false;
    }

    if (descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe ingresar una descripción del incidente.");
        return false;
    }


    if (montoTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe ingresar un monto.");
        return false;
    }

    try {
        double monto = Double.parseDouble(montoTexto);
        if (monto < 0) {
            JOptionPane.showMessageDialog(null, "El monto debe ser un valor positivo.");
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El monto debe ser un número válido.");
        return false;
    }


    return true;
}

public void guardar(){

if (validarCamposIncidente()) {
    tipoIncidente = comboTipoIncidente.getSelectedItem().toString();
    descripcion = txtDescripcion.getText().trim();
    monto = Double.parseDouble(txtMonto.getText().trim());

    int index = comboTipo.getSelectedIndex();
    idTransaccion = idTransacicones.get(index-1); 
    
    
    in.igresarIncidente(descripcion, tipoIncidente, nombre, idTransaccion, monto);
    
    JOptionPane.showMessageDialog(rootPane, "MULTA GUARDADA", "GUARDADO", JOptionPane.INFORMATION_MESSAGE);

}else{

JOptionPane.showMessageDialog(rootPane, "HUBO UN ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

}
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboTipoIncidente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtMonto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("INCIDENTES");

        jLabel2.setText("TIPO DE INCIDENTE");

        jLabel3.setText("DESCRIPCION");

        jLabel4.setText("MONTO A COBRAR");

        comboTipoIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        txtMonto.setText("txtMonto");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel5.setText("PLACA ");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(comboTipoIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comboTipoIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            guardar();
           llenarComboVehiculosActivos();
            llenarComboTipoIncidente();
            txtDescripcion.setText("");
            txtMonto.setText("");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         frmAdmin fmadmin = new  frmAdmin(idU);
                fmadmin.setVisible(true);

                this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicidentes(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboTipoIncidente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
